## Ken Kochi
## coursera R Programming - Assignment 2 Final
## December 21, 2014 

## makeCacheMatrix is a function that takes a square matrix and generates
## a list of four functions.
##
## Assumption is that the given matrix is invertible

makeCacheMatrix <- function(x = matrix()) {
        inversevalue <- NULL              ##Variable to store the inverse of the matrix
                                          ##initialized to NULL 
        
        set <- function(y) {              ##Function that saves a new matrix
                x <<- y              
                inversevalue <<- NULL     ##Resets the variable inversevalue to NULL
        }
        
        get <- function() x               ##Function that returns the matrix
        
        setinverse <- function(solve) inversevalue <<- solve ##Function that takes as input the inverse of the
                                                             ##matrix and stores it into variable inversevalue
        
        getinverse <- function() inversevalue  ##Function that returns the variable inversevalue
        
        list(set = set,                   ##Returns the list of four functions
             get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## casheSolve takes a list generated by the makeCacheMatrix function and
## checks if the inverse of the matrix has been calculated and stored. 
## If so it returns the stored value of the inverse of the matrix. If not it 
## calculates the inverse using the solve function, stores it into the list, and returns the inverse.

cacheSolve <- function(x, ...) {
        ## Returns a matrix that is the inverse of 'x'
        inverse <- x$getinverse()               ##Gets the value of the variable inversevalue from the list
        if(!is.null(inverse)) {                 ##If variable inverse is not NULL, then the 
                message("getting cached data")  ##inverse is returned and the
                return(inverse)                 ##function exits
        }
        data <- x$get()                         ##Stores the value of the matrix into data
        inverse <- solve(data, ...)             ##Uses the solve function to calculate the inverse and store it into variable inverse
        x$setinverse(inverse)                   ##Stores the inverse into the list for later retrieval
        inverse                                 ##Returns the value of the variable inverse
}
